#:kivy 2.3.1
#:import BottomNav widget.bottom_nav.BottomNav
<HistoryScreen>:

    BoxLayout:
        orientation: "vertical"

        BoxLayout:
            orientation: "vertical"

            canvas.before:
                Color:
                    rgba: 0.96, 0.97, 1, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "History Screen"
                font_size: "30sp"
                bold: True
                color: 0.1, 0.2, 0.6, 1

        BottomNav: