#:kivy 2.3.1

#:import MDCard kivymd.uix.card.MDCard
#:import BottomNav widget.bottom_nav.BottomNav

<HistoryScreen>:

    BoxLayout:
        orientation: "vertical"

        canvas.before:
            Color:
                rgba: (0.10, 0.10, 0.10, 1) if app.theme_cls.theme_style == "Dark" else (0.96, 0.97, 1, 1)
            Rectangle:
                pos: self.pos
                size: self.size

        MDCard:
            size_hint_y: None
            height: "100dp"
            radius: [0, 0, 30, 30]
            elevation: 0

            # Keep the header blue in both themes
            md_bg_color: 0.10, 0.32, 0.82, 1

            Label:
                text: "Transaction History"
                font_size: "28sp"
                bold: True
                color: 1, 1, 1, 1

        ScrollView:

            GridLayout:
                id: transaction_container

                cols: 1
                spacing: "12dp"
                padding: "12dp"

                size_hint_y: None
                height: self.minimum_height

        BottomNav:
            size_hint_y: None
            height: "75dp"