#:kivy 2.3.1

<HomeScreen>:

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: "25dp"
        spacing: "20dp"

        Label:
            text: "PocketPilot"
            font_size: "30sp"
            bold: True
            color: 0.1, 0.2, 0.6, 1
            size_hint_y: None
            height: "50dp"

        Label:
            text: "Welcome,"
            font_size: "24sp"
            color: 0, 0, 0, 1
            size_hint_y: None
            height: "35dp"

        Label:
            text: root.user_name
            font_size: "28sp"
            bold: True
            color: 0.1, 0.2, 0.6, 1
            size_hint_y: None
            height: "40dp"

        Label:
            text: "Current Balance"
            font_size: "18sp"
            color: 0.4, 0.4, 0.4, 1
            size_hint_y: None
            height: "30dp"

        Label:
            text: "₹0.00"
            font_size: "36sp"
            bold: True
            color: 0.1, 0.6, 0.2, 1
            size_hint_y: None
            height: "60dp"

        Widget: