#:kivy 2.3.1
#:import MDRaisedButton kivymd.uix.button.MDRaisedButton

<LoginScreen>:

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1

        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: "30dp"
        spacing: "15dp"

        # ==========================================
        # TOP SPACE
        # ==========================================

        Widget:
            size_hint_y: 0.15

        # ==========================================
        # LOGIN TITLE
        # ==========================================

        Label:
            text: "Login"
            font_size: "34sp"
            bold: True
            color: 0.1, 0.2, 0.6, 1
            size_hint_y: None
            height: "50dp"

        # ==========================================
        # EMAIL
        # ==========================================

        TextInput:
            id: email_input
            hint_text: "Email"
            multiline: False
            size_hint_y: None
            height: "45dp"

        # ==========================================
        # PASSWORD
        # ==========================================

        TextInput:
            id: password_input
            hint_text: "Password"
            multiline: False
            password: True
            size_hint_y: None
            height: "45dp"

        # ==========================================
        # LOGIN BUTTON
        # ==========================================

        MDRaisedButton:
            text: "Login"
            size_hint: None, None
            size: "220dp", "45dp"
            pos_hint: {"center_x": 0.5}

            on_release:
                root.login()

        # ==========================================
        # SPACE
        # ==========================================

        Widget:
            size_hint_y: 0.05

        # ==========================================
        # SIGNUP MESSAGE
        # ==========================================

        Label:
            text: "Don't have an account?"
            color: 0, 0, 0, 1
            font_size: "14sp"
            size_hint_y: None
            height: "30dp"

        # ==========================================
        # CREATE ACCOUNT BUTTON
        # ==========================================

        MDTextButton:
            text: "Create Account"
            pos_hint: {"center_x": 0.5}

            on_release:
                app.root.current = "signup"

        # ==========================================
        # BOTTOM SPACE
        # ==========================================

        Widget:
            size_hint_y: 0.2